export { default as html } from './icons/html logo.png'
export { default as css } from './icons/css.png'
export { default as react } from './icons/react.png'
export { default as node } from './icons/nodejs.png'
export { default as js } from './icons/js.png'
export { default as express } from './icons/express js.png'
export { default as bootstrap } from './icons/bootstrap.png'
export { default as tailwind } from './icons/tailwind.png'
export { default as c } from './icons/C.png'