export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Footer } from './footer/Footer'
export { default as Home } from './home/Home'
export { default as Nav } from './navbar/Nav'
export { default as Project } from './projects/Project'
export { default as Service } from './services/Service'
export { default as Experience } from './experience/Experience'